### ISSUE TITLE
onMessage function of Webview predefined

### ISSUE THREAD

**Issue by dannyyaou** [hungdev/react-native-instagram-login#16]
when I try to start login view, this popped out.
![image](https://user-images.githubusercontent.com/8759099/41267702-1688d810-6e2f-11e8-90be-b75e3b79f536.png)
Can somebody help me out?
Thanks a lot.

version

RN: 0.40.0

**Comment by hungdev** [comment]
I think its old version lib. 
Remove react-native-instagram-login from node_modules, remove package name react-native-instagram-login from package.json then reinstall react-native-instagram-login newest version.
If it still errors, please let me know. I will fix it as soon as possible.

**Comment by maneeshprajapati** [comment]
@hungdev 2 weeks ago Instagram login was working perfectly fine in my app. But today it started throwing the same error. I'm not sure why this is happening. I will try your solution and will update if it works.

**Comment by maneeshprajapati** [comment]
@hungdev installed the latest version of lib but this issue is still occurring. When I dismiss this error it shows Instagram login popup on screen. After a successful login this error screen appears again and after dismissing this it shows Instagram logged user details on popup. Can you please help me out of this?

**Comment by hungdev** [comment]
updated. please try again.
